repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
        exclude: ^docs/assets/
      - id: trailing-whitespace
        exclude: ^docs/assets/
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.7
    hooks:
      - id: clang-format
        files: \.(c|cc|cpp|cxx|cu|cuh|h|hh|hpp|hxx)$
