name: Check clang-format

on:
  pull_request:

jobs:
  check-clang-format:
    name: proteus
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Install clang-format
        run: pip install clang-format==18.1.8
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: Run clang-format
        run: git clang-format --diff origin/${{ github.base_ref }}
