name: cpp-linter

on:
  pull_request:
    #paths:
    #  - "common/*"
    #  - "pass/*"
    #  - "lib/*"

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: 18
          ignore: .github | tests | scripts
          style: file
          tidy-checks: ''
          lines-changed-only: true
          format-review: true
          tidy-review: true

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed != 0
        run: exit 1
