# Simple workflow for deploying static content to GitHub Pages
name: docs (gh-pages)

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    paths:
      - "docs/**"
      - "include/**"
      - "src/**"
      - "mkdocs.yml"
      - ".github/workflows/deploy-pages-main.yml"
      - ".github/workflows/gh-pages-docs.yml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      contents: write
    uses: ./.github/workflows/deploy-pages-main.yml
