# Simple workflow for deploying static content to GitHub Pages
name: docs (gh-pages)

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: ./.github/workflows/deploy-pages.yml
    with:
      host-backend-package: proteus-python-backend-host-llvm22
      cuda-backend-package: proteus-python-backend-cuda12-llvm22
      rocm-backend-package: proteus-python-backend-rocm72
